# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xtbTBKm_PMJF3MRXTEROHT7R7LVLZFyx

# **Analysis by using sklearn library**
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
# Load dataset from device
data = pd.read_csv('/content/student_data.csv')

# #convert the values 'Yes' and 'No' in the "Extracurricular Activities" column to 1 and 0, respectively.
data['Extracurricular Activities'] = data['Extracurricular Activities'].map({'Yes': 1, 'No': 0})

# Assuming the target column is named 'target'
target_column = 'Performance'

# Extract features and target variable
X = data.drop(columns=[target_column])
y = data[target_column]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

# Initialize the Linear Regression model
model = LinearRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate Mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)